default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: rebidx_development

test:
  <<: *default
  database: rebidx_test

production:
  <<: *default
  # Render provides DATABASE_URL, so use it if present
  url: <%= ENV['DATABASE_URL'] %>
